### ISSUE TITLE
Own Entry in new line

### ISSUE THREAD

**Issue by Avalarion** [customink-webops/hostsfile#40]
Hey ho,

I am currently trying to write a lot of things in my /etc/hosts file and I am totally new to chef. This Recipe is pretty easy and I tried to understand it on my own, but as I had to figure out I have got too less skills in ruby to create a new version with pull request so here is what I would like to have:

``` ruby
action :create_own
```

which is not appending another ip block, but in stead writing a new line.

Example:

``` ruby
hostsfile_entry '1.2.3.4' do
  hostname 'dev.local'
end
```

``` ruby
hostsfile_entry '1.2.3.4' do
  hostname 'prod.local'
  action :append
end
```

will create:

```
1.2.3.4 dev.local prod.local
```

But I would like to have:

```
1.2.3.4 dev.local
1.2.3.4 prod.local
```

Is this a possible feature?

**Comment by jorhett** [comment]
"The point of working with configuration management is that you never manually make configuration changes on a server."

Valid, however that doesn't change that humans use the system and humans don't tend to read lines which are >120 characters long.  So there is a problem in that it is necessary to put multiple lines with the same IP so that humans who are debugging can easily view which hosts are where, or grep and get just  a single hostname on a line.

Likewise, certain servers are used primarily by QA, and will often stop chef and make manual changes to test something. They then re-enable chef knowing it will return the environment to standard config. Commenting out a single hostfile entry is much easier than deleting it from a long line.

This is "for the convenience of humans" request, and is very necessary in our environment.  

So my reply here is "machines are made to do things to make it easier for humans" and "it really isn't hard to do" so why not?
